// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {profiles} from '../models';
import {proxy} from '../models';

export function AddEnvironment(arg1:profiles.Environment):Promise<void>;

export function AddPACDomain(arg1:string):Promise<void>;

export function ApplyEnvMapping(arg1:string,arg2:string):Promise<void>;

export function DeleteEnvironment(arg1:string):Promise<void>;

export function GetActiveEnv():Promise<profiles.Environment>;

export function GetEnvConfigNames():Promise<Array<string>>;

export function GetEnvironments():Promise<Array<profiles.Environment>>;

export function GetMocks():Promise<Array<proxy.MockRule>>;

export function GetPACAddr():Promise<string>;

export function GetPACDomains():Promise<Array<string>>;

export function GetProxyAddr():Promise<string>;

export function GetRewriteRules():Promise<Array<profiles.RewriteRule>>;

export function ImportEnvConfig(arg1:string):Promise<void>;

export function OpenFilePicker():Promise<string>;

export function OpenInChrome():Promise<void>;

export function RemovePACDomain(arg1:string):Promise<void>;

export function SetActiveEnv(arg1:string):Promise<void>;

export function SetMocks(arg1:Array<proxy.MockRule>):Promise<void>;

export function SetRewriteRules(arg1:Array<profiles.RewriteRule>):Promise<void>;

export function StartRecording():Promise<void>;

export function StopRecording():Promise<string>;

export function UpdateEnvironment(arg1:profiles.Environment):Promise<void>;
