// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddEnvironment(arg1) {
  return window['go']['main']['App']['AddEnvironment'](arg1);
}

export function DeleteEnvironment(arg1) {
  return window['go']['main']['App']['DeleteEnvironment'](arg1);
}

export function GetActiveEnv() {
  return window['go']['main']['App']['GetActiveEnv']();
}

export function GetEnvironments() {
  return window['go']['main']['App']['GetEnvironments']();
}

export function GetProxyAddr() {
  return window['go']['main']['App']['GetProxyAddr']();
}

export function GetRewriteRules() {
  return window['go']['main']['App']['GetRewriteRules']();
}

export function SetActiveEnv(arg1) {
  return window['go']['main']['App']['SetActiveEnv'](arg1);
}

export function SetRewriteRules(arg1) {
  return window['go']['main']['App']['SetRewriteRules'](arg1);
}

export function UpdateEnvironment(arg1) {
  return window['go']['main']['App']['UpdateEnvironment'](arg1);
}
