// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetProxyAddr() {
  return window['go']['main']['App']['GetProxyAddr']();
}

export function GetRewriteRules() {
  return window['go']['main']['App']['GetRewriteRules']();
}

export function SetRewriteRules(arg1) {
  return window['go']['main']['App']['SetRewriteRules'](arg1);
}
