// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddEnvironment(arg1) {
  return window['go']['main']['App']['AddEnvironment'](arg1);
}

export function AddPACDomain(arg1) {
  return window['go']['main']['App']['AddPACDomain'](arg1);
}

export function ApplyEnvMapping(arg1, arg2) {
  return window['go']['main']['App']['ApplyEnvMapping'](arg1, arg2);
}

export function DeleteEnvironment(arg1) {
  return window['go']['main']['App']['DeleteEnvironment'](arg1);
}

export function GetActiveEnv() {
  return window['go']['main']['App']['GetActiveEnv']();
}

export function GetEnvConfigNames() {
  return window['go']['main']['App']['GetEnvConfigNames']();
}

export function GetEnvironments() {
  return window['go']['main']['App']['GetEnvironments']();
}

export function GetMocks() {
  return window['go']['main']['App']['GetMocks']();
}

export function GetPACAddr() {
  return window['go']['main']['App']['GetPACAddr']();
}

export function GetPACDomains() {
  return window['go']['main']['App']['GetPACDomains']();
}

export function GetProxyAddr() {
  return window['go']['main']['App']['GetProxyAddr']();
}

export function GetRewriteRules() {
  return window['go']['main']['App']['GetRewriteRules']();
}

export function ImportEnvConfig(arg1) {
  return window['go']['main']['App']['ImportEnvConfig'](arg1);
}

export function OpenFilePicker() {
  return window['go']['main']['App']['OpenFilePicker']();
}

export function OpenInChrome() {
  return window['go']['main']['App']['OpenInChrome']();
}

export function RemovePACDomain(arg1) {
  return window['go']['main']['App']['RemovePACDomain'](arg1);
}

export function SetActiveEnv(arg1) {
  return window['go']['main']['App']['SetActiveEnv'](arg1);
}

export function SetMocks(arg1) {
  return window['go']['main']['App']['SetMocks'](arg1);
}

export function SetRewriteRules(arg1) {
  return window['go']['main']['App']['SetRewriteRules'](arg1);
}

export function StartRecording() {
  return window['go']['main']['App']['StartRecording']();
}

export function StopRecording() {
  return window['go']['main']['App']['StopRecording']();
}

export function UpdateEnvironment(arg1) {
  return window['go']['main']['App']['UpdateEnvironment'](arg1);
}
