// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {profiles} from '../models';

export function AddEnvironment(arg1:profiles.Environment):Promise<void>;

export function DeleteEnvironment(arg1:string):Promise<void>;

export function GetActiveEnv():Promise<profiles.Environment>;

export function GetEnvironments():Promise<Array<profiles.Environment>>;

export function GetProxyAddr():Promise<string>;

export function GetRewriteRules():Promise<Array<profiles.RewriteRule>>;

export function SetActiveEnv(arg1:string):Promise<void>;

export function SetRewriteRules(arg1:Array<profiles.RewriteRule>):Promise<void>;

export function UpdateEnvironment(arg1:profiles.Environment):Promise<void>;
